name: cdk-ci-actions
on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Biome
        run: npx biome ci .
      - name: Run Cdk
        run: npx cdk list
